%initPicassoToolbox
%pollyDataFile = 'H:\\picasso_io\\pollyxt_cpv\\data_zip\\202403\\2024_03_08_Fri_CPV_00_00_01.nc';
pollyDataFile = 'C:\\_data\\Picasso_IO\\pollyxt_cpv\\data_zip\\202403\\2024_03_08_Fri_CPV_00_00_01.nc';
%pollyConfigFile = 'H:\\Pollynet_Processing_Chain\\config\\pollyConfigs\\pollyxt_tropos_config_20230418-2.json'
%pollyConfigFile = 'H:\\Pollynet_Processing_Chain\\config\\pollyConfigs\\pollyxt_cpv_2021.txt';
pollyConfigFile = 'C:\\_data\\Picasso_IO\\configs\\pollyConfigs\\pollyxt_cpv_2021.txt';
%PicassoConfigFile = 'H:\\Pollynet_Processing_Chain\\config\\pollynet_processing_chain_config_rsd2_24h_exp.json';
PicassoConfigFile = 'C:\\_data\\Picasso_IO\\pollynet_processing_chain_config_PC_mod.json';

%PicassoConfig = loadConfig(PicassoConfigFile, 'H:\\Pollynet_Processing_Chain\\lib\config\\pollynet_processing_chain_config.json');
PicassoConfig = loadConfig(PicassoConfigFile, PicassoConfigFile);
%PollyConfig = loadPollyConfig(pollyConfigFile, 'H:\\Pollynet_Processing_Chain\\lib\config\\polly_global_config.json');
PollyConfig = loadPollyConfig(pollyConfigFile, 'C:\\_data\\PicassoPy\\Pollynet_Processing_Chain\\lib\\config\\polly_global_config.json');
%data = readPollyRawData(pollyDataFile, 'flagFilterFalseMShots', PollyConfig.flagFilterFalseMShots,'flagCorrectFalseMShots', PollyConfig.flagCorrectFalseMShots,'flagDeleteData', PicassoConfig.flagDeleteData,'dataFileFormat', PollyConfig.dataFileFormat,'deltaT', PollyConfig.deltaT);
data = readPollyRawData(pollyDataFile, ...
            'flagFilterFalseMShots', PollyConfig.flagFilterFalseMShots, ...
            'flagCorrectFalseMShots', PollyConfig.flagCorrectFalseMShots, ...
            'flagDeleteData', PicassoConfig.flagDeleteData, ...
            'dataFileFormat', PollyConfig.dataFileFormat, ...
            'deltaT', PollyConfig.deltaT);
        
 %% Specify channel tags
[channelTags, channelLabels, flagFarRangeChannel, flagNearRangeChannel, flagRotRamanChannel, flagTotalChannel, flagCrossChannel, flagParallelChannel, flag355nmChannel, flag387nmChannel, flag407nmChannel, flag532nmChannel, flag607nmChannel, flag1064nmChannel] = pollyChannelTags(PollyConfig.channelTags, ...
    'flagFarRangeChannel', PollyConfig.isFR, ...
    'flagNearRangeChannel', PollyConfig.isNR, ...
    'flagRotRamanChannel', PollyConfig.isRR, ...
    'flagTotalChannel', PollyConfig.isTot, ...
    'flagCrossChannel', PollyConfig.isCross, ...
    'flagParallelChannel', PollyConfig.isParallel, ...
    'flag355nmChannel', PollyConfig.is355nm, ...
    'flag387nmChannel', PollyConfig.is387nm, ...
    'flag407nmChannel', PollyConfig.is407nm, ...
    'flag532nmChannel', PollyConfig.is532nm, ...
    'flag607nmChannel', PollyConfig.is607nm, ...
    'flag1064nmChannel', PollyConfig.is1064nm);
data.channelTags = channelTags;
data.channelLabels = channelLabels;
data.flagFarRangeChannel = flagFarRangeChannel;
data.flagNearRangeChannel = flagNearRangeChannel;
data.flagRotRamanChannel = flagRotRamanChannel;
data.flagTotalChannel = flagTotalChannel;
data.flagCrossChannel = flagCrossChannel;
data.flagParallelChannel = flagParallelChannel;
data.flag355nmChannel = flag355nmChannel;
data.flag387nmChannel = flag387nmChannel;
data.flag407nmChannel = flag407nmChannel;
data.flag532nmChannel = flag532nmChannel;
data.flag607nmChannel = flag607nmChannel;
data.flag1064nmChannel = flag1064nmChannel;


CampaignConfig = struct();
CampaignConfig.name = 'CVO';
CampaignConfig.location = 'Mindelo';
CampaignConfig.startTime = '20210601';
CampaignConfig.endTime = '20290101';
CampaignConfig.lon = -25.0;
CampaignConfig.lat = 16.8;
CampaignConfig.asl = 13;

%% Pre-processing
data_pre = pollyPreprocess(data, ...
            'deltaT', PollyConfig.deltaT, ...
            'flagForceMeasTime', PollyConfig.flagForceMeasTime, ...
            'maxHeightBin', PollyConfig.max_height_bin, ...
            'firstBinIndex', PollyConfig.first_range_gate_indx, ...
            'firstBinHeight', PollyConfig.first_range_gate_height, ...
            'pollyType', CampaignConfig.name, ...
            'flagDeadTimeCorrection', PollyConfig.flagDTCor, ...
            'deadtimeCorrectionMode', PollyConfig.dtCorMode, ...
            'deadtimeParams', PollyConfig.dt, ...
            'flagSigTempCor', PollyConfig.flagSigTempCor, ...
            'tempCorFunc', PollyConfig.tempCorFunc, ...
            'meteorDataSource', PollyConfig.meteorDataSource, ...
            'gdas1Site', PollyConfig.gdas1Site, ...
            'meteo_folder', PollyConfig.meteo_folder, ...
            'radiosondeSitenum', PollyConfig.radiosondeSitenum, ...
            'radiosondeFolder', PollyConfig.radiosondeFolder, ...
            'radiosondeType', PollyConfig.radiosondeType, ...
            'bgCorrectionIndex', PollyConfig.bgCorRangeIndx, ...
            'asl', CampaignConfig.asl, ...
            'initialPolAngle', PollyConfig.init_depAng, ...
            'maskPolCalAngle', PollyConfig.maskDepCalAng, ...
            'minSNRThresh', PollyConfig.mask_SNRmin, ...
            'minPC_fog', PollyConfig.minPC_fog, ...
            'flagFarRangeChannel', data.flagFarRangeChannel, ...
            'flag532nmChannel', data.flag532nmChannel, ...
            'flagTotalChannel', data.flagTotalChannel, ...
            'flag355nmChannel', data.flag355nmChannel, ...
            'flag607nmChannel', data.flag607nmChannel, ...
            'flag387nmChannel', data.flag387nmChannel, ...
            'flag407nmChannel', data.flag407nmChannel, ...
            'flag355nmRotRaman', data.flag355nmChannel & data.flagRotRamanChannel, ...
            'flag532nmRotRaman', data.flag532nmChannel & data.flagRotRamanChannel, ...
            'flag1064nmRotRaman', data.flag1064nmChannel & data.flagRotRamanChannel, ...
            'isUseLatestGDAS', PollyConfig.flagUseLatestGDAS);
